<?php

namespace AppBundle\Repository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return array
     */
    public function getAuthorSummary()
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a.id, a.name, a.firstName, count(p) as numberOfPosts')
            ->innerJoin('a.posts', 'p')
            ->groupBy('p.author');

        return $qb->getQuery()->getArrayResult();
    }
}
