app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_check_route:
    path: /admin-login-check

admin_logout:
    path: /admin-logout

author_check_route:
    path: /author-login-check

author_logout:
    path: /author-logout
