# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.hello:
        class: AppBundle\Services\HelloService
        arguments: ["@security.token_storage"]
        tags: [{name: kernel.event_suscriber}]
